version: "3.3"
services:
  app:
    build: .
    command: sh -c "yarn && yarn dev"
    environment:
      PROJECT_ENV: development
      #Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
